### PR TITLE
Added pattern scanning, improved misc. stuff

### PR DESCRIPTION
**Pull request by lolp1**
-Pattern scanning added (tested)

-x64 support improved via project settings/peb/misc small changes

-Better events in MemorySharp.cs (process data/error output handlers, process exit handlers, standard protected event raise methods)

Here is full working example to test patterns (x64 live WoW legion EnumVisibleObjects function pointer pattern)

``` csharp

using System;
using System.Linq;

namespace TestApp
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var process = System.Diagnostics.Process.GetProcessesByName("Wow-64").FirstOrDefault();

            var memorySharp = new Binarysharp.MemoryManagement.MemorySharp(process);

            var patternScanner = memorySharp.Modules.MainModule.GetPatternScanner();



            var scanResult =
                patternScanner.Find(
                    new Binarysharp.MemoryManagement.Patterns.DwordPattern(
                      "48 89 74 24 ?? 57 48 83 EC 20 48 8B 05 ?? ?? ?? ?? 48 8B F1 48 8B FA 48 8B 88 ?? ?? ?? ?? F6 C1 01 75 05 48 85 C9 75 02"));

            if (!scanResult.ScanWasSuccessful)
            {
                Console.WriteLine("Could not find pattern.");
            }

            Console.WriteLine(scanResult.Offset.ToString("X"));
            Console.WriteLine(scanResult.BaseAddress.ToString("X"));
            Console.WriteLine(scanResult.RebasedAddress.ToString("X"));

            Console.ReadLine();
        }
    }
}
```

### CODE REVIEW

**Comment by ZenLulz** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;Hyqyg183&#x2F;6-64-bit-support"> 64-bit support.</a>

**Comment by lolp1** [comment]
I should mention that this is built on the newest .NET framework version...

**Comment by Zaczero** [comment]
Finally pattern scan function 👍

**Comment by lolp1** [comment]
Any updates on any new progress ^^?

**Comment by JamesMenetrey** [comment]
I'll focus on 64-bit first :D

**Comment by lolp1** [comment]
@ZenLulz Can you just close this request and keep it as a reference? The idea is a good start but is not really a good fit with your deepening branch.

**Pull request closed without merging**
